name: CI - Build & Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build And Test
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Package
        run: ./mvwn clean package
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_21_x64 || '' }}
